const lessons=[
{title:"Why specs matter",tag:"THE MINDSET",body:"Agentic development delegates implementation steps to tools that can inspect, edit, and run code. A spec gives people and agents a shared, reviewable definition of success.",points:["A prompt is a request; a specification is a durable contract.","Capture the problem, actors, outcomes, boundaries, and observable success.","Avoid promising correctness merely because an agent produced plausible code."],tip:"Ask: how would a reviewer know the feature works without reading the author's mind?"},
{title:"Write testable intent",tag:"SPECIFY",body:"Start with user outcomes, not implementation choices. Record functional behavior, non-functional constraints, and explicit out-of-scope items.",points:["Write concrete user stories and measurable acceptance criteria.","Include errors, authorization, empty states, and accessibility.","Record assumptions and unanswered questions; clarify before implementation."],tip:"Instead of ‘fast export’, specify a representative dataset and measurable response-time target."},
{title:"Plan the work",tag:"PLAN",body:"Turn approved requirements into architecture decisions and thin, independently verifiable tasks. Keep implementation options separate from product requirements.",points:["Inspect existing code and repository instructions first.","Identify affected modules, data contracts, security and migration risks.","Sequence small tasks with test expectations and rollback considerations."],tip:"Have the agent propose a plan and ask for approval at consequential decision points."},
{title:"Guide coding agents",tag:"IMPLEMENT",body:"Agents can explore repositories, edit files, execute tests, and iterate. Give them bounded scope, least-privilege tools, and explicit stop conditions.",points:["Use AGENTS.md to record setup, conventions and test commands.","Prefer focused diffs and short feedback loops over giant unreviewable changes.","Never paste secrets into prompts; review destructive commands and external side effects."],tip:"Ask the agent to report modified files, test commands, outcomes, and remaining uncertainty."},
{title:"Converge on evidence",tag:"VERIFY",body:"Compare the implementation against each acceptance criterion. Tests, reviews, and real user flows provide different kinds of evidence.",points:["Trace every requirement to a test, inspection, or manual check.","Run unit, integration, security and accessibility checks as appropriate.","Review the diff, failed tests and known limitations before merging."],tip:"A green test suite is evidence, not proof that the specification was complete."},
{title:"Operate & improve",tag:"ITERATE",body:"Specifications evolve with feedback. Preserve decisions, verification records and unresolved risks so future humans and agents can continue safely.",points:["Version specs alongside code and document decisions.","Watch production behavior and turn regressions into new tests.","Adjust process weight to risk; avoid ceremony for its own sake."],tip:"Close the loop: observed failure → revised criterion → regression test → fix."}
];
const lessonSources=[[0,5],[1,2],[1,2],[3,4,5],[2,5,6],[0,6]];
const sourceCatalog=[{"name":"Spec Kit methodology","url":"https://github.github.com/spec-kit/"},{"name":"Spec Kit quickstart","url":"https://github.com/github/spec-kit/blob/main/docs/quickstart.md"},{"name":"Spec Kit agentic reference","url":"https://github.github.com/spec-kit/reference/agentic-sdd.html"},{"name":"AGENTS.md","url":"https://agents.md/"},{"name":"OpenAI Codex safety","url":"https://openai.com/index/running-codex-safely/"},{"name":"OpenAI Codex introduction","url":"https://openai.com/index/introducing-codex/"},{"name":"OpenAI Cookbook","url":"https://github.com/openai/openai-cookbook/blob/main/examples/codex/iterating-development-workflows-with-codex.md"}];
const nav=document.querySelector('#lessonsNav'), view=document.querySelector('#lesson');
let done;try{done=JSON.parse(localStorage.getItem('sdd-done')||'[]')}catch{done=[]}if(!Array.isArray(done))done=[];
let current=0;
function render(){nav.innerHTML='';lessons.forEach((l,i)=>{const b=document.createElement('button');b.textContent=(done.includes(i)?'✓ ':'0'+(i+1)+' · ')+l.title;b.className=i===current?'active':'';b.setAttribute('aria-current',i===current?'step':'false');b.onclick=()=>{current=i;render()};nav.append(b)});const l=lessons[current];view.innerHTML='<article class="lessoncard"><span class="eyebrow">LESSON '+String(current+1).padStart(2,'0')+' / '+l.tag+'</span><h3>'+l.title+'</h3><p>'+l.body+'</p><ul>'+l.points.map(p=>'<li>'+p+'</li>').join('')+'</ul><blockquote><strong>TRY THIS</strong><br>'+l.tip+'</blockquote>'+ '<p class="small lesson-source">Evidence &amp; reading: '+lessonSources[current].map(i=>'<a target="_blank" rel="noopener noreferrer" href="'+sourceCatalog[i].url+'">'+sourceCatalog[i].name+' ↗</a>').join(' · ')+'</p></article>';document.querySelector('#progressbar').style.width=(done.length/lessons.length*100)+'%';document.querySelector('#progresslabel').textContent=done.length+' of '+lessons.length+' completed';document.querySelector('#prev').disabled=current===0;document.querySelector('#complete').textContent=done.includes(current)?'Next lesson →':'Mark complete & continue →'}
document.querySelector('#prev').onclick=()=>{current=Math.max(0,current-1);render()};document.querySelector('#complete').onclick=()=>{if(!done.includes(current)){done.push(current);try{localStorage.setItem('sdd-done',JSON.stringify(done))}catch{}}current=Math.min(current+1,lessons.length-1);render()};document.querySelector('#start').onclick=()=>document.querySelector('#learn').scrollIntoView({behavior:'smooth'});render();
const prompt='Write a specification for authenticated task CSV export. Include actors, goals, scope, authorization, CSV format/escaping, empty state, failure behavior, non-functional constraints, open questions, and Given/When/Then acceptance criteria. Do not implement until ambiguities are reviewed.';
document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(prompt);document.querySelector('#copy').textContent='Copied ✓'}catch{window.prompt('Copy this prompt:',prompt)}};
const questions=[{q:'What belongs in a feature specification?',a:['Only the preferred programming language','Observable user behavior and acceptance criteria','A large unreviewed agent prompt'],correct:1,why:'Specify the what and why before committing to the how.'},{q:'An agent reports that all tests pass. What next?',a:['Merge without review','Delete the spec','Check coverage of acceptance criteria and review the diff'],correct:2,why:'Passing tests cannot establish that the tests cover every requirement.'},{q:'How should an agent handle unclear authorization rules?',a:['Ask for clarification before implementing','Guess the simplest policy','Ignore the edge case'],correct:0,why:'Security-relevant ambiguity should be resolved explicitly.'}];
const quiz=document.querySelector('#quiz');questions.forEach((q,i)=>{const section=document.createElement('div');section.className='question';const heading=document.createElement('h3');heading.textContent=(i+1)+'. '+q.q;section.append(heading);const feedback=document.createElement('p');feedback.className='feedback';feedback.setAttribute('role','status');q.a.forEach((a,j)=>{const b=document.createElement('button');b.textContent=a;b.onclick=()=>{feedback.textContent=(j===q.correct?'Correct. ':'Not quite. ')+q.why};section.append(b)});section.append(feedback);quiz.append(section)});
